### ISSUE TITLE
Use proxys in OpenBulletToPython

### ISSUE THREAD

**Issue by lokigamer00** [Categorically/OpenBulletToPython#16]
how i can use proxys in this library?

**Comment by Categorically** [comment]
You can add HTTP proxies to the Requests lib.
https://docs.python-requests.org/en/master/user/advanced/#proxies

From OpenBullet2Python/Functions/Requests/Requests.py
OBRequest.Perform()
This handles the requests before they are sent you can add proxies to "self.session.send()" like you would with requests.foo
